---
title: "ImageClassify"
author: "HYHsiao"
date: "2024-03-23"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load('tidyverse','readr')
ggplot2::theme_set(theme_minimal())
```

read data file

```{r}
performances <- read_csv("D:/1122_DeepLearning/HW1/performances.txt", col_names=FALSE)
colnames(performances) <- c('feature', 'classifier', 'training_size', 'n_classes', 'index', 'score')
predictions_detailed <- read_csv("D:/1122_DeepLearning/HW1/predictions_detailed.txt", col_names=FALSE)
colnames(predictions_detailed) <- c('feature', 'classifier', 'training_size', 'n_classes', 'class_T', 'class_P', 'correct')
```

Including Plots

```{r}
l_size = 50
t_size = 100
performances |> 
  dplyr::filter(index=='F1-score') |>
  dplyr::filter(training_size==t_size) |>
  dplyr::filter(n_classes==l_size) |>
  ggplot() + 
  aes(x=feature, y=score, color=classifier, group=classifier) +
  geom_point(size=3, position=position_dodge(.2)) +
  theme(legend.position='top') +
  labs(x='Features', y='F1-score')
ggsave("IC_exp1_F1.png", width= 4, height= 3)

performances |> 
  dplyr::filter(index=='Accuracy') |>
  dplyr::filter(training_size==t_size) |>
  dplyr::filter(n_classes==l_size) |>
  ggplot() + 
  geom_hline(yintercept=1/l_size, linetype="dashed") +
  aes(x=feature, y=score, color=classifier, group=classifier) +
  geom_point(size=3, position=position_dodge(.2)) +
  theme(legend.position='top') +
  labs(x='Features', y='Accuracy')
ggsave("IC_exp1_acc.png", width= 4, height= 3)
```

```{r}
t_size = 100
performances |> 
  dplyr::filter(index=='F1-score') |>
  dplyr::filter(training_size==t_size) |>
  dplyr::filter(feature %in% c('sift','color_histogram')) |>
  dplyr::filter(classifier %in% c('KNN','XGBoost')) |>
  ggplot() + 
  aes(x=n_classes, y=score, color=feature, group=feature) +
  geom_point(size=3, position=position_dodge(15)) +
  facet_wrap(vars(classifier), nrow=1) +
  theme(legend.position='top') +
  labs(x='Categories', y='F1-score')
ggsave("IC_exp2_F1.png", width= 4, height= 3)

performances |> 
  dplyr::filter(index=='Accuracy') |>
  dplyr::filter(training_size==t_size) |>
  dplyr::filter(feature %in% c('sift','color_histogram')) |>
  dplyr::filter(classifier %in% c('KNN','XGBoost')) |>
  ggplot() +
  stat_function(fun = \(x) 1/x, linetype = "dashed", color = "black") + 
  aes(x=n_classes, y=score, color=feature, group=feature) +
  geom_point(size=3, position=position_dodge(15)) +
  facet_wrap(vars(classifier), nrow=1) +
  theme(legend.position='top') +
  labs(x='Categories', y='Accuracy')
ggsave("IC_exp2_acc.png", width= 4, height= 3)
```

```{r}
l_size = 50
performances |> 
  dplyr::filter(index=='F1-score') |>
  dplyr::filter(n_classes==l_size) |>
  dplyr::filter(feature %in% c('sift','color_histogram')) |>
  dplyr::filter(classifier %in% c('KNN','XGBoost')) |>
  mutate(training_size = as.factor(training_size)) |>
  ggplot() + 
  aes(x=training_size, y=score, color=feature, group=feature) +
  geom_point(size=3, position=position_dodge(0.3)) +
  facet_wrap(vars(classifier), nrow=1) +
  theme(legend.position='top') +
  labs(x='Images/each Category', y='F1-score')
ggsave("IC_exp3_F1.png", width= 4, height= 3)

performances |> 
  dplyr::filter(index=='Accuracy') |>
  dplyr::filter(n_classes==l_size) |>
  dplyr::filter(feature %in% c('sift','color_histogram')) |>
  dplyr::filter(classifier %in% c('KNN','XGBoost')) |>
  mutate(training_size = as.factor(training_size)) |>
  ggplot() + 
  geom_hline(yintercept=1/l_size, linetype="dashed") +
  aes(x=training_size, y=score, color=feature, group=feature) +
  geom_point(size=3, position=position_dodge(0.3)) +
  facet_wrap(vars(classifier), nrow=1) +
  theme(legend.position='top') +
  labs(x='Images/each Category', y='Accuracy')
ggsave("IC_exp3_acc.png", width= 4, height= 3)
```

